openapi: 3.0.3
info:
  title: Account Microservice API
  version: 1.0.0
  description: Gestión de cuentas bancarias con validación de cliente y reglas de negocio

servers:
  - url: http://localhost:8081

paths:
  /cuentas:
    post:
      summary: Crear cuenta bancaria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Cuenta creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Datos inválidos o cliente no encontrado
    get:
      summary: Listar todas las cuentas
      responses:
        '200':
          description: Lista de cuentas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountResponse'

  /cuentas/{id}:
    get:
      summary: Obtener cuenta por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cuenta encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '404':
          description: Cuenta no encontrada
    delete:
      summary: Eliminar cuenta
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Cuenta eliminada
        '404':
          description: Cuenta no encontrada

  /cuentas/{cuentaId}/depositar:
    put:
      summary: Depositar en cuenta
      parameters:
        - name: cuentaId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
      responses:
        '200':
          description: Depósito exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '400':
          description: Monto inválido

  /cuentas/{cuentaId}/retirar:
    put:
      summary: Retirar de cuenta
      parameters:
        - name: cuentaId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawRequest'
      responses:
        '200':
          description: Retiro exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '400':
          description: Monto inválido o sobregiro no permitido

components:
  schemas:
    CreateAccountRequest:
      type: object
      required: [clientId, type, initialBalance]
      properties:
        clientId:
          type: integer
        type:
          type: string
          enum: [CHECKING, SAVING]
        initialBalance:
          type: number
          format: double
          minimum: 0.01

    DepositRequest:
      type: object
      required: [amount]
      properties:
        amount:
          type: number
          format: double
          minimum: 0.01

    WithdrawRequest:
      type: object
      required: [amount]
      properties:
        amount:
          type: number
          format: double
          minimum: 0.01

    AccountResponse:
      type: object
      properties:
        id:
          type: integer
        accountNumber:
          type: string
        balance:
          type: number
          format: double
        type:
          type: string
        clientId:
          type: integer

    BalanceResponse:
      type: object
      properties:
        id:
          type: integer
        balance:
          type: number
          format: double
